### ISSUE TITLE
Login Flow V2

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#20]
Login flow V2 is browser based but also needs a preparation call and a polling call to finish the login flow. I would contribute those two if you do not mind having them in the library. Since they are purely between target client and NC server I believe being in the library is okay. NC docs: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2

**Comment by provokateurin** [comment]
There is actually already an implementation living in https://github.com/Viktoriaschule/dart-nextcloud/tree/feature/notifications.

**Comment by vauvenal5** [comment]
I just took a look, the LoginFlow part looks rather complete, I guess some work on notifications is still open? Any idea when to expect this merged?

Would it be an idea to cherry pick the login flow code into a separate feature branch and merge it independently? I would be willing to do that, if you do not have time.

I saw that you changed the API of the `NextCloudClient` to handle the `port` separately, although it is not used yet. I believe this might be a dangerous move since a Nextcloud base path can also be behind a sub path like: `https://my.cloud.com:8080/nc`
If you want more fine grained access to the URI parts why not use the [Dart URI](https://api.dart.dev/stable/2.10.4/dart-core/Uri-class.html) class as parameter for the client instead of `string`?

**Comment by provokateurin** [comment]
Yeah I stopped working on the notification code, because the app is not maintained anymore. Still it is complete and works iirc.
I like the idea of using a Dart URI.
The problem I have with that branch is that it's just one commit which changes a lot of things. If you want to you can cherry pick the login flow changes and add the Dart URI (best would be two separate PRs). I will then later create new commits with all the other changes (these would be splitting the tests and implementing notifications iirc).

**Comment by vauvenal5** [comment]
Okay sounds great, I will get started. :+1:

**Comment by provokateurin** [comment]
Btw if you need the client implementation in flutter you can take a look at https://github.com/Viktoriaschule/App/blob/feature/nextcloud-talk/features/nextcloud_talk/lib/src/nextcloud_talk_login_dialog.dart

**Comment by vauvenal5** [comment]
How far would you go regarding the `Uri`? I mean should the sub-clients be also refactored to work with a Uri or just on main client level?

I think for the beginning main client is enough since we are not yet doing anything with Uri parts.

**Comment by provokateurin** [comment]
> I think for the beginning main client is enough since we are not yet doing anything with Uri parts.

Agree
