### ISSUE TITLE
Allow User-Agent to be passed from outside

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#26]
The user-agent is used for the login flow to display to the user what client is requesting access, therefore, it should be possible to pass it from outside.

**Comment by provokateurin** [comment]
I did try modifying it, but for whatever reason it didn't work in my flutter app. It still might work in pure dart or I had something configured wrong in the flutter app

**Comment by vauvenal5** [comment]
I tried it out with the login test against the dev instance. We simply have to send it to the NC server with the initial request of the flow. I will provide a PR today or tomorrow.

**Comment by vauvenal5** [comment]
I thought a little bit about this and maybe the best approach is to allow passing a set of default headers to the nextcloud client. This way if the need arises for additional application specific headers they can easily be passed.
