### ISSUE TITLE
Sub-Url bug in WebDavFile path

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#30]
There is an issue when the Nextcloud server is behind a sub-path, for example `https://cloud.com/nc`. When parsing the XML returned by the server `replaceAll` replaces the `davUrl` in the file path but leaves the `nc` part of the server path in there. A split operation would probably be a better option to make sure that the parts belonging to the server address are cut away.

Sorry when reviewing the file path handling PR I did not think of it, just came to mind now when I was about to integrate the newest version of the library.

**Comment by provokateurin** [comment]
Would you mind creating a PR to fix it? Also adding a test would be good, but I'm not sure how to add the sub path to the docker image.
