### ISSUE TITLE
Nextcloud activity log support

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#32]
As far as I saw currently the activity log endpoint is not supported: https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md

I am opening this here also to have the docs for the API at the right place, however, at the moment I do not have time to contribute this feature. But, if no one else tackles this first, I will get back to it, eventually. :+1:

**Comment by provokateurin** [comment]
Looking to implement that in Nextcloud Neon :) https://github.com/jld3103/dart-nextcloud/issues/32
