### ISSUE TITLE
WebDavFile get name failes when folder name looks like uri component

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#37]
If a folder is named like `:443` and placed in the directory root of the Nextcloud server then a `FormatException` gets thrown when `webDavFile.name` is called because `Uri.parse` fails to recognize it as a name.

**Comment by provokateurin** [comment]
I'm not sure if there is anything to do about it, because there is no way to tell the difference. Otherwise `Uri.parse` should work, right?

**Comment by provokateurin** [comment]
I think they way to fix this would be escaping the path characters with URL encoding.
I'll try to reproduce this with a test and then fix it.

**Comment by provokateurin** [comment]
@vauvenal5 could you provide me a hint on what operation it fails? I don't know how your app works and the logs from the issue don't tell me anything on what it's actually failing.

**Comment by provokateurin** [comment]
In my test case where I create a folder named `:443`, upload a file and list the directory, everything works as expected.

**Comment by provokateurin** [comment]
Ah I was able to trigger it I think.

**Comment by vauvenal5** [comment]
Sry for the late response. I was not at the computer any longer.

**Comment by provokateurin** [comment]
No problem
