### ISSUE TITLE
remote.php/webdav vs remote.php/dav

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#4]
There are two occurrences of `remote.php/webdav` in the code where I strongly suspect that it is a typo and should be `remote.php/dav`. Am I missing something?

https://github.com/Viktoriaschule/dart-nextcloud/blob/a6f917036a5205ab0eef88ed90065309d4960a9e/lib/src/webdav/client.dart#L33

https://github.com/Viktoriaschule/dart-nextcloud/blob/a6f917036a5205ab0eef88ed90065309d4960a9e/lib/src/webdav/file.dart#L81

**Comment by provokateurin** [comment]
Me and @fingeg were also wondering why there are two occurences with different paths. It is a bit unclear for me how it happened in the first place, but the only correct path seems to be without `web`. 

If you give me a few minutes I will update the library.

**Comment by provokateurin** [comment]
Fixed in `v1.1.1`
