### ISSUE TITLE
remote.php/dav is appended twice

### ISSUE THREAD

**Issue by vauvenal5** [Viktoriaschule/dart-nextcloud#5]
The `WebDavClient` appends `remote.php/dav/` twice to the provided url. Once in the constructor and once in `_getUrl` function. This leads to a wrong url.

https://github.com/Viktoriaschule/dart-nextcloud/blob/f99a79b3590ac572a3d5952a3cba149840d6772e/lib/src/webdav/client.dart#L17
https://github.com/Viktoriaschule/dart-nextcloud/blob/f99a79b3590ac572a3d5952a3cba149840d6772e/lib/src/webdav/client.dart#L35

**Comment by provokateurin** [comment]
Oh thanks. Overlooked that, because I'm working on new features and I was copying only parts of the correct code.

**Comment by provokateurin** [comment]
Closed in `1.1.2`
