### ISSUE TITLE
How to implement OAuth 2.0 with Flutter and NextCloud?

### ISSUE THREAD

**Issue by wsegatto** [Viktoriaschule/dart-nextcloud#53]
I'm new to Flutter/Dart.
I'm struggling a lot to be able to use an authentication other than the basic hardcoded user/password, which I understand is not a good practice, but is the only example shown in the plugin.

Does anyone have been able to implement this and could share it pleeease?

All the examples I found were related to user authentication, which is not what I want, I want to access NextCloud services in the background, not something the user will see. Other examples had limited implementations and the examples talked a lot about having to open the browser for a redirect to happen? This is not what I would expect. 

Anyway, again, I'm new to this. Let me know your thoughts for a best practice approach.

Thank you in advance!
Will

**Comment by provokateurin** [comment]
Hi,
as far as I know there is no way to implement a native login.
You always have to use the webview to log in.
This implementation might help you implementing it on your own: https://github.com/Viktoriaschule/App/blob/feature/nextcloud-talk/features/nextcloud_talk/lib/src/nextcloud_talk_login_dialog.dart

**Comment by provokateurin** [comment]
If you don't want any user interaction you should use an app password which can be revoked by the user at any point.
