### ISSUE TITLE
mkdirs does not work as expected

### ISSUE THREAD

**Issue by PascalOtto** [Viktoriaschule/dart-nextcloud#57]
Hello thank you for this package,

mkdirs-method for the WebDav-Module claims to work like mkdir -p.

Expected Behavior:
if I call _mkdirs_ with **path="/folder1/folder2/folder3"** I should get:

![Screenshot 2022-02-09 182400](https://user-images.githubusercontent.com/43848718/153255618-2a49695f-3154-4be5-b8b1-3d2234b01bdc.png)

Actual Behavior:

The method splits the directorynames up and creates them on the same directory-level.

![Screenshot 2022-02-09 182533](https://user-images.githubusercontent.com/43848718/153255886-5adab8b7-8db5-4e78-9a4f-df7e7a149b54.png)

**Comment by provokateurin** [comment]
Can you show the code you used to create the folders?

**Comment by PascalOtto** [comment]
@jld3103 I opened #58 addressing the issue

**Comment by pastordee** [comment]
Hi guys I got mine to work by using the mkdir and saving the one folder at time.
  var userId = "${globals.currentUser!.objectId!}";
  String user= 'Users';
  String userId = 'Users/$userId';
  String finalFolder = '$userId/profile_pics';
then I save the file.
await client.webDav.upload(image.readAsBytesSync(), '$finalFolder/avatar.jpg')

So I think in the mkdirs we have to find a way to get it to loop through everything and save it one by one.
If you were saving up to 2 levels of folder it will be something like this

`Future mkdirs(String path) async {
    path = path.trim();
    final dirs = path.split('/')..removeWhere((value) => value == '');
    if (dirs.isEmpty) {
      return;
    }
    if (path.startsWith('/')) {
      dirs[0] = '/${dirs[0]}';
      print(dirs);
    }
    await mkdir(dirs[0]);
    var increment = 1;
    for (final dir in dirs) {
      print(dir);
      
      await mkdir(dirs[0]+'/'+dirs[increment]);
      increment++;
    }
  }`

**Comment by provokateurin** [comment]
Fixed in https://github.com/jld3103/nextcloud-neon/blob/4f7c506c0134442706a8638cb7b10c62f2337b2a/packages/nextcloud/lib/src/clients/custom/webdav/client.dart
