### ISSUE TITLE
Error parser Cliente->User->MetaData

### ISSUE THREAD

**Issue by ArRiMartinez** [Viktoriaschule/dart-nextcloud#59]
When trying to consume the method client.users.getMetaData(userId);
Return the following error:
Expected a value of type 'List<String>', but got one of type 'List<dynamic>'

The error occurs in the MetaData class

`  Future<MetaData> getMetaData(String username) async {
    final url = '$_baseUrl/$username';
    final response = await _network.send('GET', url, [200]);
    return MetaData.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }`

Code
`/// MetaData class
class MetaData {
  // ignore: public_member_api_docs
  MetaData(
    this.fullName,
    this.groups,
  );

  // ignore: public_member_api_docs
  factory MetaData.fromJson(Map<String, dynamic> json) => MetaData(
        json['ocs']['data']['displayname'] as String,
        json['ocs']['data']['groups'] as List<String>,
      );

  // ignore: public_member_api_docs
  final String fullName;

  // ignore: public_member_api_docs
  final List<String> groups;

  @override
  String toString() => 'MetaData{fullName: $fullName ,groups: $groups}}';
}
`
**Therefore, add the MetaDataUser class, which does not return an error.**

`  Future<MetaDataUser > getMetaData(String username) async {
    final url = '$_baseUrl/$username';
    final response = await _network.send('GET', url, [200]);
    return MetaDataUser .fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }`
`
class MetaDataUser {
  Ocs? _ocs;

  MetaDataUser({Ocs? ocs}) {
    if (ocs != null) {
      this._ocs = ocs;
    }
  }

  Ocs? get ocs => _ocs;
  set ocs(Ocs? ocs) => _ocs = ocs;

  MetaDataUser.fromJson(Map<String, dynamic> json) {
    _ocs = json['ocs'] != null ? new Ocs.fromJson(json['ocs']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._ocs != null) {
      data['ocs'] = this._ocs!.toJson();
    }
    return data;
  }
}

class Ocs {
  Meta? _meta;
  Data? _data;

  Ocs({Meta? meta, Data? data}) {
    if (meta != null) {
      this._meta = meta;
    }
    if (data != null) {
      this._data = data;
    }
  }

  Meta? get meta => _meta;
  set meta(Meta? meta) => _meta = meta;
  Data? get data => _data;
  set data(Data? data) => _data = data;

  Ocs.fromJson(Map<String, dynamic> json) {
    _meta = json['meta'] != null ? new Meta.fromJson(json['meta']) : null;
    _data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._meta != null) {
      data['meta'] = this._meta!.toJson();
    }
    if (this._data != null) {
      data['data'] = this._data!.toJson();
    }
    return data;
  }
}

class Meta {
  String? _status;
  int? _statuscode;
  String? _message;
  String? _totalitems;
  String? _itemsperpage;

  Meta(
      {String? status,
      int? statuscode,
      String? message,
      String? totalitems,
      String? itemsperpage}) {
    if (status != null) {
      this._status = status;
    }
    if (statuscode != null) {
      this._statuscode = statuscode;
    }
    if (message != null) {
      this._message = message;
    }
    if (totalitems != null) {
      this._totalitems = totalitems;
    }
    if (itemsperpage != null) {
      this._itemsperpage = itemsperpage;
    }
  }

  String? get status => _status;
  set status(String? status) => _status = status;
  int? get statuscode => _statuscode;
  set statuscode(int? statuscode) => _statuscode = statuscode;
  String? get message => _message;
  set message(String? message) => _message = message;
  String? get totalitems => _totalitems;
  set totalitems(String? totalitems) => _totalitems = totalitems;
  String? get itemsperpage => _itemsperpage;
  set itemsperpage(String? itemsperpage) => _itemsperpage = itemsperpage;

  Meta.fromJson(Map<String, dynamic> json) {
    _status = json['status'];
    _statuscode = json['statuscode'];
    _message = json['message'];
    _totalitems = json['totalitems'];
    _itemsperpage = json['itemsperpage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this._status;
    data['statuscode'] = this._statuscode;
    data['message'] = this._message;
    data['totalitems'] = this._totalitems;
    data['itemsperpage'] = this._itemsperpage;
    return data;
  }
}

class Data {
  bool? _enabled;
  String? _storageLocation;
  String? _id;
  int? _lastLogin;
  String? _backend;
  List<String>? _subadmin;
  Quota? _quota;
  Null? _email;
  String? _displayname;
  String? _phone;
  String? _address;
  String? _website;
  String? _twitter;
  List<String>? _groups;
  String? _language;
  String? _locale;
  BackendCapabilities? _backendCapabilities;

  Data(
      {bool? enabled,
      String? storageLocation,
      String? id,
      int? lastLogin,
      String? backend,
      List<String>? subadmin,
      Quota? quota,
      Null? email,
      String? displayname,
      String? phone,
      String? address,
      String? website,
      String? twitter,
      List<String>? groups,
      String? language,
      String? locale,
      BackendCapabilities? backendCapabilities}) {
    if (enabled != null) {
      this._enabled = enabled;
    }
    if (storageLocation != null) {
      this._storageLocation = storageLocation;
    }
    if (id != null) {
      this._id = id;
    }
    if (lastLogin != null) {
      this._lastLogin = lastLogin;
    }
    if (backend != null) {
      this._backend = backend;
    }
    if (subadmin != null) {
      this._subadmin = subadmin;
    }
    if (quota != null) {
      this._quota = quota;
    }
    if (email != null) {
      this._email = email;
    }
    if (displayname != null) {
      this._displayname = displayname;
    }
    if (phone != null) {
      this._phone = phone;
    }
    if (address != null) {
      this._address = address;
    }
    if (website != null) {
      this._website = website;
    }
    if (twitter != null) {
      this._twitter = twitter;
    }
    if (groups != null) {
      this._groups = groups;
    }
    if (language != null) {
      this._language = language;
    }
    if (locale != null) {
      this._locale = locale;
    }
    if (backendCapabilities != null) {
      this._backendCapabilities = backendCapabilities;
    }
  }

  bool? get enabled => _enabled;
  set enabled(bool? enabled) => _enabled = enabled;
  String? get storageLocation => _storageLocation;
  set storageLocation(String? storageLocation) =>
      _storageLocation = storageLocation;
  String? get id => _id;
  set id(String? id) => _id = id;
  int? get lastLogin => _lastLogin;
  set lastLogin(int? lastLogin) => _lastLogin = lastLogin;
  String? get backend => _backend;
  set backend(String? backend) => _backend = backend;
  List<String>? get subadmin => _subadmin;
  set subadmin(List<String>? subadmin) => _subadmin = subadmin;
  Quota? get quota => _quota;
  set quota(Quota? quota) => _quota = quota;
  Null? get email => _email;
  set email(Null? email) => _email = email;
  String? get displayname => _displayname;
  set displayname(String? displayname) => _displayname = displayname;
  String? get phone => _phone;
  set phone(String? phone) => _phone = phone;
  String? get address => _address;
  set address(String? address) => _address = address;
  String? get website => _website;
  set website(String? website) => _website = website;
  String? get twitter => _twitter;
  set twitter(String? twitter) => _twitter = twitter;
  List<String>? get groups => _groups;
  set groups(List<String>? groups) => _groups = groups;
  String? get language => _language;
  set language(String? language) => _language = language;
  String? get locale => _locale;
  set locale(String? locale) => _locale = locale;
  BackendCapabilities? get backendCapabilities => _backendCapabilities;
  set backendCapabilities(BackendCapabilities? backendCapabilities) =>
      _backendCapabilities = backendCapabilities;

  Data.fromJson(Map<String, dynamic> json) {
    _enabled = json['enabled'];
    _storageLocation = json['storageLocation'];
    _id = json['id'];
    _lastLogin = json['lastLogin'];
    _backend = json['backend'];
    _subadmin = json['subadmin'].cast<String>();
    _quota = json['quota'] != null ? new Quota.fromJson(json['quota']) : null;
    _email = json['email'];
    _displayname = json['displayname'];
    _phone = json['phone'];
    _address = json['address'];
    _website = json['website'];
    _twitter = json['twitter'];
    _groups = json['groups'].cast<String>();
    _language = json['language'];
    _locale = json['locale'];
    _backendCapabilities = json['backendCapabilities'] != null
        ? new BackendCapabilities.fromJson(json['backendCapabilities'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['enabled'] = this._enabled;
    data['storageLocation'] = this._storageLocation;
    data['id'] = this._id;
    data['lastLogin'] = this._lastLogin;
    data['backend'] = this._backend;
    data['subadmin'] = this._subadmin;
    if (this._quota != null) {
      data['quota'] = this._quota!.toJson();
    }
    data['email'] = this._email;
    data['displayname'] = this._displayname;
    data['phone'] = this._phone;
    data['address'] = this._address;
    data['website'] = this._website;
    data['twitter'] = this._twitter;
    data['groups'] = this._groups;
    data['language'] = this._language;
    data['locale'] = this._locale;
    if (this._backendCapabilities != null) {
      data['backendCapabilities'] = this._backendCapabilities!.toJson();
    }
    return data;
  }
}

class Quota {
  int? _free;
  int? _used;
  int? _total;
  int? _relative;
  int? _quota;

  Quota({int? free, int? used, int? total, int? relative, int? quota}) {
    if (free != null) {
      this._free = free;
    }
    if (used != null) {
      this._used = used;
    }
    if (total != null) {
      this._total = total;
    }
    if (relative != null) {
      this._relative = relative;
    }
    if (quota != null) {
      this._quota = quota;
    }
  }

  int? get free => _free;
  set free(int? free) => _free = free;
  int? get used => _used;
  set used(int? used) => _used = used;
  int? get total => _total;
  set total(int? total) => _total = total;
  int? get relative => _relative;
  set relative(int? relative) => _relative = relative;
  int? get quota => _quota;
  set quota(int? quota) => _quota = quota;

  Quota.fromJson(Map<String, dynamic> json) {
    _free = json['free'];
    _used = json['used'];
    _total = json['total'];
    _relative = json['relative'];
    _quota = json['quota'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['free'] = this._free;
    data['used'] = this._used;
    data['total'] = this._total;
    data['relative'] = this._relative;
    data['quota'] = this._quota;
    return data;
  }
}

class BackendCapabilities {
  bool? _setDisplayName;
  bool? _setPassword;

  BackendCapabilities({bool? setDisplayName, bool? setPassword}) {
    if (setDisplayName != null) {
      this._setDisplayName = setDisplayName;
    }
    if (setPassword != null) {
      this._setPassword = setPassword;
    }
  }

  bool? get setDisplayName => _setDisplayName;
  set setDisplayName(bool? setDisplayName) => _setDisplayName = setDisplayName;
  bool? get setPassword => _setPassword;
  set setPassword(bool? setPassword) => _setPassword = setPassword;

  BackendCapabilities.fromJson(Map<String, dynamic> json) {
    _setDisplayName = json['setDisplayName'];
    _setPassword = json['setPassword'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['setDisplayName'] = this._setDisplayName;
    data['setPassword'] = this._setPassword;
    return data;
  }
}
`

**Comment by provokateurin** [comment]
Fixed in https://github.com/jld3103/nextcloud-neon/tree/4f7c506c0134442706a8638cb7b10c62f2337b2a/packages/nextcloud/lib/src/clients/generated/provisioning_api
