### ISSUE TITLE
How to check if a client is connected?

### ISSUE THREAD

**Issue by JesperBellenbaum** [Viktoriaschule/dart-nextcloud#9]
Nice work! Glad to have this plugin. 

It would be nice if the client would provide a possibility to check if it was initialised with valid credentials. Any ideas how to do this?

Thanks for your great work again :)

**Comment by provokateurin** [comment]
I think there is some kind of status API, but you can also use any endpoint and if you get a 401 status code the user isn't logged in.

**Comment by serhatkrc** [comment]
Thanks for informations,
Can you help me with a subject I'm stuck on?
I want to search within the folder. How can I do it?
Also how can I view pdf.

**Comment by JesperBellenbaum** [comment]
@jld3103 thanks for the quick reply. I might will create a PR for the "official" login flow (https://docs.nextcloud.com/server/18/developer_manual/client_apis/LoginFlow/index.html).

**Comment by provokateurin** [comment]
I already implemented login flow v2. I have it only locally, because there are some other changes I also made, but they don't need to be included for now. I'll just push the login flow implementation in the next few days

**Comment by JesperBellenbaum** [comment]
Oh okay, does it also include already a WebView and a possibility to safely store the credentials? I guess than I don't need to go on.. 👍

**Comment by provokateurin** [comment]
This is a pure dart package so no flutter parts, but I can add a flutter example using the code from my app.

**Comment by vauvenal5** [comment]
I will be uploading the code of my app this weekend. There is a full login flow example with flutters webview. Works like a charm.

**Comment by vauvenal5** [comment]
Here you go a Nextcloud login flow example with the Flutter webview: https://github.com/vauvenal5/yaga/blob/master/lib/views/screens/nc_login_screen.dart

**Comment by provokateurin** [comment]
The login flow implementation lives in https://github.com/Viktoriaschule/dart-nextcloud/tree/feature/notifications. I forgot I already pushed it. I has some breaking changes, but you can look at the example or tests

**Comment by provokateurin** [comment]
The user endpoint is now implemented (https://github.com/Viktoriaschule/dart-nextcloud/pull/19) and should be used for such purposes.
